version: '3.1'

#http://localhost:15672/#/ RabbitMq Management Console
services:
  spring-boot-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672   #Arayuz portu
      - 5672:5672     #Kuyruk portu
    environment:
      - RABBITMQ_DEFAULT_USER=ugurcan
      - RABBITMQ_DEFAULT_PASS=password
